version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10
    working_directory: /go/src/github.com/tnolet/terraform-provider-checkly
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go test -v ./...

  deploy:
    docker:
      - image: circleci/golang:1.10
    working_directory: /go/src/github.com/tnolet/terraform-provider-checkly
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go get -u github.com/mitchellh/gox
      - run: go get -u github.com/tcnksm/ghr
      - run:
          name: cross compile
          command: |
            gox -os="linux darwin windows" -arch="amd64" -output="dist/terraform-provider-checkly_{{.OS}}_{{.Arch}}"
            cd dist/ && gzip *
      - add_ssh_keys
      - run:
          name: create release
          command: |
            ghr -t $GITHUB_TOKEN -u tnolet -r terraform-provider-checkly --replace $CIRCLE_TAG dist/
        
workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
            tags:
              only: /^v.*/